version: "3.7"
services:
  api:
    build:
      args:        
        php_version: ${PHP_VERSION}        
      context: ./
      dockerfile: Dockerfile
    image: dockerphp
    container_name: dockerphp-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./api:/var/www
    networks:
      - dockerphp

  db:
    image: mysql:8.0
    container_name: dockerphp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${USER}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - dockerphp

  nginx:
    image: nginx:alpine
    container_name: dockerphp-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./api:/var/www/
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - dockerphp

networks:
  dockerphp:
    driver: bridge
